name: ctrlx-bacnet-mstp
base: core22
version: "0.1"
summary: BACnet MS/TP datalayer interface
description: |
  ctrlX Data Layer node provider for BACnet MS/TP devices

# NOTE --- Must build mstplib shared object manually prior to snapping

grade: stable
confinement: strict

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]

apps:
  provider:
    daemon: simple
    command: bin/main.py
    plugs:
      - network
      - datalayer
      - network-bind
      - serial-port
      - raw-usb
      - active-solution
    slots:
      - package-assets
    restart-condition: always
    passthrough:
      restart-delay: 10s

parts:
  # ctrlX provider (Python app + deps)
  provider:
    plugin: python
    source: ./provider-source
    stage-packages:
      - ctrlx-datalayer

  # Misty libs
  misty:
    plugin: python
    source: ./misty
    build-packages:
      - build-essential
      - python3-dev

    # Prevent duplicate package staging
    stage:
      - -lib/python3.10/site-packages/pip*
      - -lib/python3.10/site-packages/wheel*
      - -lib/python3.10/site-packages/setuptools/
      - -lib/python3.10/site-packages/_distutils_hack
      - -lib/python3.10/site-packages/pkg_resources
      - -bin/activate
      - -bin/activate.csh
      - -bin/activate.fish
      - -pyvenv.cfg

  # Ship default configs
  config:
    plugin: dump
    source: ./config
    organize:
      'package-assets/*': package-assets/${CRAFT_PROJECT_NAME}/

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
        - $SNAP/package-assets/${CRAFT_PROJECT_NAME}

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer

  active-solution:
    interface: content
    content: solutions
    target: $SNAP_COMMON/solutions

lint:
  ignore:
    - library:
      - usr/lib/aarch64-linux-gnu/libcomm_datalayer.so.*
      - usr/lib/x86_64-linux-gnu/libcomm_datalayer.so.*